name: 'BetonQuestExtras'
version: '${version}'
main: cc.mewcraft.betonquest.Main
api-version: 1.19
depend: [ helper, BetonQuest ]
softdepend: [ Towny, ItemsAdder ]
authors: [ Nailm ]
description: Brings BetonQuest more integrations with 3rd party plugins.
